# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version (latest LTS)
      - image: circleci/node:8.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce

      - run: yarn
      - run: yarn run lint
      # - run: make docker-build

      - deploy:
          name: Publish Docker Image
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" || -n "${CIRCLE_TAG}" ]]; then
              if [[ -n "${CIRCLE_TAG}" ]]; then
                docker tag kubeapps/dashboard:latest kubeapps/dashboard:${CIRCLE_TAG}
              fi
              docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
              docker push kubeapps/dashboard
            fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v[0-9].*$/
